#include "scheduler/service/worker_deploy_service.h"

#include <cctype>
#include <spdlog/spdlog.h>
#include <sstream>
#include "common/util/ssh_executor.h"

namespace taskflow::scheduler::service {

namespace {

// Escape a string for safe inclusion in a YAML double-quoted scalar.
// We use double-quoted scalars and escape backslash and double-quote.
std::string yamlDoubleQuote(const std::string& s) {
    std::string out;
    out.reserve(s.size() + 2);
    for (char c : s) {
        if (c == '\\') {
            out += "\\\\";
        } else if (c == '"') {
            out += "\\\"";
        } else if (static_cast<unsigned char>(c) < 0x20) {
            // control chars -> escape as needed (rare in config values)
            out += "\\x";
            char hex[3];
            std::snprintf(hex, sizeof(hex), "%02x", static_cast<unsigned char>(c));
            out += hex;
        } else {
            out += c;
        }
    }
    return "\"" + out + "\"";
}

// Escape a string so it can be safely embedded inside single quotes in a
// POSIX shell command. Each single quote becomes '\'' (close quote, escaped
// quote, reopen quote).
std::string shellSingleQuote(const std::string& s) {
    std::string out;
    out.reserve(s.size() + 2);
    for (char c : s) {
        if (c == '\'') {
            out += "'\\''";
        } else {
            out += c;
        }
    }
    return "'" + out + "'";
}

// Sanitize a worker name into a filesystem-safe filename component so each
// worker gets its own config file on a shared remote node (avoiding
// overwrites between multiple workers in the same remote_dir).
// Allowed: letters, digits, '-', '_', '.'. Everything else becomes '_'.
// Falls back to "worker" if the result is empty or all-unsafe chars.
std::string sanitizeFileName(const std::string& name) {
    std::string out;
    out.reserve(name.size());
    for (char c : name) {
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '-' || c == '_' || c == '.') {
            out += c;
        } else {
            out += '_';
        }
    }
    if (out.empty() || out.find_first_not_of("._-") == std::string::npos) {
        return "worker";
    }
    return out;
}

}  // namespace

nlohmann::json WorkerDeployResult::toJson() const {
    nlohmann::json steps_arr = nlohmann::json::array();
    for (const auto& s : steps) {
        steps_arr.push_back({
            {"step", s.step},
            {"success", s.success},
            {"message", s.message}
        });
    }
    return {
        {"success", success},
        {"worker_name", worker_name},
        {"address", address},
        {"config_path", config_path},
        {"steps", steps_arr},
        {"message", message}
    };
}

common::result::Result<void> WorkerDeployService::validate(const WorkerDeployRequest& req) {
    if (req.name.empty()) {
        return common::result::Result<void>::failure("worker 名称不能为空");
    }
    if (req.host.empty()) {
        return common::result::Result<void>::failure("机器 IP (host) 不能为空");
    }
    if (req.grpc_port <= 0 || req.grpc_port > 65535) {
        return common::result::Result<void>::failure("grpc_port 必须在 1-65535 之间");
    }
    if (req.ssh_port <= 0 || req.ssh_port > 65535) {
        return common::result::Result<void>::failure("ssh_port 必须在 1-65535 之间");
    }
    if (req.ssh_username.empty()) {
        return common::result::Result<void>::failure("SSH 用户名不能为空");
    }
    if (req.ssh_password.empty()) {
        return common::result::Result<void>::failure("SSH 密码不能为空");
    }
    if (req.scheduler_address.empty()) {
        return common::result::Result<void>::failure("scheduler_address 不能为空");
    }
    if (req.max_tasks <= 0) {
        return common::result::Result<void>::failure("max_tasks 必须大于 0");
    }
    if (req.worker_binary_path.empty()) {
        return common::result::Result<void>::failure("worker_binary_path 不能为空");
    }
    if (req.remote_dir.empty()) {
        return common::result::Result<void>::failure("remote_dir 不能为空");
    }
    return common::result::Result<void>();
}

std::string WorkerDeployService::generateWorkerConfig(const WorkerDeployRequest& req) {
    // The worker's advertised address (what the scheduler dials back to) is
    // host:grpc_port.
    std::string advertise_address = req.host + ":" + std::to_string(req.grpc_port);

    std::ostringstream ss;
    ss << "# Auto-generated by TaskFlow scheduler worker deployment\n";
    ss << "server:\n";
    ss << "  grpc_port: " << req.grpc_port << "\n";
    ss << "  advertise_address: " << yamlDoubleQuote(advertise_address) << "\n";
    ss << "  tls:\n";
    ss << "    enabled: false\n";
    ss << "\n";
    ss << "scheduler:\n";
    ss << "  address: " << yamlDoubleQuote(req.scheduler_address) << "\n";
    ss << "  tls:\n";
    ss << "    enabled: false\n";
    ss << "\n";
    ss << "worker:\n";
    ss << "  name: " << yamlDoubleQuote(req.name) << "\n";
    ss << "  max_tasks: " << req.max_tasks << "\n";
    ss << "  resource_tags:";
    if (req.resource_tags.empty()) {
        ss << " []\n";
    } else {
        ss << "\n";
        for (const auto& tag : req.resource_tags) {
            ss << "    - " << yamlDoubleQuote(tag) << "\n";
        }
    }
    ss << "\n";
    ss << "log:\n";
    ss << "  level: " << yamlDoubleQuote(req.log_level.empty() ? "info" : req.log_level) << "\n";
    ss << "  file_path: logs/worker.log\n";
    ss << "\n";
    ss << "task_log:\n";
    ss << "  dir: logs/tasks\n";
    ss << "  retention_days: 30\n";

    return ss.str();
}

common::result::Result<WorkerDeployResult> WorkerDeployService::deploy(const WorkerDeployRequest& req) {
    auto v = validate(req);
    if (!v.ok()) {
        return common::result::Result<WorkerDeployResult>::failure(v.error());
    }

    WorkerDeployResult result;
    result.worker_name = req.name;
    result.address = req.host + ":" + std::to_string(req.grpc_port);

    common::util::SshExecutor ssh(req.host, req.ssh_port, req.ssh_username, req.ssh_password);

    // Step 1: test connectivity.
    {
        DeployStepLog log{"SSH 连接测试", false, ""};
        auto t = ssh.testConnection(15);
        if (!t.ok()) {
            log.message = t.error();
            result.steps.push_back(log);
            result.success = false;
            result.message = "SSH 连接失败: " + t.error();
            return result;
        }
        log.success = true;
        log.message = "连接成功 " + req.ssh_username + "@" + req.host + ":" + std::to_string(req.ssh_port);
        result.steps.push_back(log);
    }

    // Step 2: create working directories on the remote host.
    {
        DeployStepLog log{"创建远程目录", false, ""};
        std::string mkdir_cmd =
            "mkdir -p " + req.remote_dir + "/logs/tasks";
        auto r = ssh.execute(mkdir_cmd, 30);
        if (!r.ok()) {
            log.message = r.error();
            result.steps.push_back(log);
            result.success = false;
            result.message = "创建远程目录失败: " + r.error();
            return result;
        }
        const auto& cr = r.value();
        if (cr.exit_code != 0) {
            log.message = "exit=" + std::to_string(cr.exit_code) + ": " + cr.output;
            result.steps.push_back(log);
            result.success = false;
            result.message = "创建远程目录失败: " + cr.output;
            return result;
        }
        log.success = true;
        log.message = req.remote_dir + "/logs/tasks";
        result.steps.push_back(log);
    }

    // Step 3: write the worker config file.
    // Use the worker name as the filename so multiple workers in the same
    // remote_dir don't overwrite each other's config (e.g. worker-1.yaml,
    // worker-2.yaml).
    std::string config_path = req.remote_dir + "/" + sanitizeFileName(req.name) + ".yaml";
    result.config_path = config_path;
    {
        DeployStepLog log{"写入配置文件", false, ""};
        std::string content = generateWorkerConfig(req);
        auto w = ssh.writeFile(config_path, content, "644", 30);
        if (!w.ok()) {
            log.message = w.error();
            result.steps.push_back(log);
            result.success = false;
            result.message = "写入配置文件失败: " + w.error();
            return result;
        }
        log.success = true;
        log.message = config_path + " (" + std::to_string(content.size()) + " bytes)";
        result.steps.push_back(log);
    }

    // Step 4: check the worker binary exists on the remote host.
    {
        DeployStepLog log{"检查 worker 可执行文件", false, ""};
        std::string check_cmd = "test -x " + req.worker_binary_path + " && echo ok || echo missing";
        auto r = ssh.execute(check_cmd, 15);
        if (!r.ok()) {
            log.message = r.error();
            result.steps.push_back(log);
            result.success = false;
            result.message = "检查 worker 可执行文件失败: " + r.error();
            return result;
        }
        const auto& cr = r.value();
        if (cr.output.find("ok") == std::string::npos) {
            log.message = "未找到可执行的 worker: " + req.worker_binary_path;
            result.steps.push_back(log);
            result.success = false;
            result.message = log.message + "（请先在目标机器安装 worker 并设置可执行权限）";
            return result;
        }
        log.success = true;
        log.message = req.worker_binary_path;
        result.steps.push_back(log);
    }

    // Step 5: start the worker with setsid, detaching it from the SSH session.
    // The worker reads its config via --config and self-registers with the
    // scheduler over gRPC on startup.
    {
        DeployStepLog log{"启动 worker", false, ""};
        // setsid: create a new session so the worker detaches from the SSH
        // session's process group and controlling terminal (CentOS 7's setsid
        // command supports this basic usage; only -w is missing). Combined
        // with redirecting all three standard fds away from the SSH channel
        // (stdin=/dev/null, stdout/stderr=log file), this minimizes the chance
        // that the worker keeps the SSH channel open.
        //
        // Tolerance for SSH hang: on some OpenSSH versions (e.g. CentOS 7's
        // 7.4) the worker may still inherit a channel fd copy, so the ssh
        // client hangs waiting for channel EOF. We handle this below: if ssh
        // times out but the output already contains "started_pid=", the
        // setsid launch succeeded and the worker is running remotely — killing
        // the local ssh does NOT affect the detached worker.
        std::string start_cmd =
            "cd " + req.remote_dir + " && "
            "setsid " + req.worker_binary_path + " --config " + config_path +
            " < /dev/null >> " + req.remote_dir + "/logs/worker.log 2>&1 &"
            " echo started_pid=$!";
        auto r = ssh.execute(start_cmd, 15);
        if (!r.ok()) {
            log.message = r.error();
            result.steps.push_back(log);
            result.success = false;
            result.message = "启动 worker 失败: " + r.error();
            return result;
        }
        const auto& cr = r.value();
        // Determine whether the worker actually launched:
        //  - Normal: exit_code=0, output contains started_pid
        //  - SSH hang timeout: timed_out=true, exit_code=124, but output still
        //    contains started_pid (the launch command ran; only the ssh channel
        //    failed to close). The detached worker keeps running on the node.
        bool launched = cr.output.find("started_pid=") != std::string::npos;
        if (launched) {
            log.success = true;
            log.message = "已启动: " + req.worker_binary_path + " --config " + config_path;
            if (!cr.output.empty()) {
                log.message += " (" + cr.output + ")";
            }
            if (cr.timed_out) {
                log.message += " [SSH 通道未正常关闭，但 worker 已启动并运行]";
            }
            result.steps.push_back(log);
        } else {
            log.message = "exit=" + std::to_string(cr.exit_code) + ": " + cr.output;
            result.steps.push_back(log);
            result.success = false;
            result.message = "启动 worker 失败: " + cr.output;
            return result;
        }
    }

    // Step 6: briefly verify the process is still alive (not crashed on boot).
    // Non-fatal: this is a best-effort diagnostic. The worker self-registers
    // via gRPC, so the worker list is the source of truth. A detection miss
    // (race, unusual ps format) should NOT fail an otherwise-successful deploy.
    {
        DeployStepLog log{"检查进程存活", false, ""};
        // Give the worker a moment to either boot or crash.
        ssh.execute("sleep 2", 10);
        // Portable check: use `ps` + `grep` (works on CentOS 7 which lacks
        // pgrep). Match on the worker binary path with fixed-string grep to
        // avoid regex issues with paths, and exclude grep itself. `ps -e -o
        // args=` is available on CentOS/RHEL/Ubuntu; fall back to `ps -ef` if
        // the first form errors out.
        std::string check_cmd =
            "ps -e -o args= 2>/dev/null | grep -F " + shellSingleQuote(req.worker_binary_path) +
            " | grep -v grep | grep -q . && echo alive || "
            "(ps -ef 2>/dev/null | grep -F " + shellSingleQuote(req.worker_binary_path) +
            " | grep -v grep | grep -q . && echo alive || echo dead)";
        auto r = ssh.execute(check_cmd, 15);
        bool alive = r.ok() && r.value().output.find("alive") != std::string::npos;
        if (alive) {
            log.success = true;
            log.message = "worker 进程运行中";
        } else {
            // Detection failed — surface the tail of the worker log to aid
            // debugging, but do NOT fail the deploy (the process may have
            // started after our check, or ps output format differed).
            auto logtail = ssh.execute("tail -n 20 " + req.remote_dir + "/logs/worker.log 2>&1", 10);
            std::string tail = logtail.ok() ? logtail.value().output : "";
            log.success = true;  // still mark success; this is informational
            log.message = "未在 ps 中检测到 worker 进程（可能仍在启动或 ps 格式差异），"
                           "请到节点列表确认是否注册成功。日志末尾:\n" + tail;
        }
        result.steps.push_back(log);
    }

    result.success = true;
    result.message = "worker 部署成功，已通过 SSH 启动。worker 将自动向 scheduler (" +
                     req.scheduler_address + ") 注册，稍后将出现在节点列表中。";
    return result;
}

}  // namespace taskflow::scheduler::service
