#include "scheduler/service/worker_deploy_service.h"

#include <spdlog/spdlog.h>
#include <sstream>
#include "common/util/ssh_executor.h"

namespace taskflow::scheduler::service {

namespace {

// Escape a string for safe inclusion in a YAML double-quoted scalar.
// We use double-quoted scalars and escape backslash and double-quote.
std::string yamlDoubleQuote(const std::string& s) {
    std::string out;
    out.reserve(s.size() + 2);
    for (char c : s) {
        if (c == '\\') {
            out += "\\\\";
        } else if (c == '"') {
            out += "\\\"";
        } else if (static_cast<unsigned char>(c) < 0x20) {
            // control chars -> escape as needed (rare in config values)
            out += "\\x";
            char hex[3];
            std::snprintf(hex, sizeof(hex), "%02x", static_cast<unsigned char>(c));
            out += hex;
        } else {
            out += c;
        }
    }
    return "\"" + out + "\"";
}

}  // namespace

nlohmann::json WorkerDeployResult::toJson() const {
    nlohmann::json steps_arr = nlohmann::json::array();
    for (const auto& s : steps) {
        steps_arr.push_back({
            {"step", s.step},
            {"success", s.success},
            {"message", s.message}
        });
    }
    return {
        {"success", success},
        {"worker_name", worker_name},
        {"address", address},
        {"config_path", config_path},
        {"steps", steps_arr},
        {"message", message}
    };
}

common::result::Result<void> WorkerDeployService::validate(const WorkerDeployRequest& req) {
    if (req.name.empty()) {
        return common::result::Result<void>::failure("worker 名称不能为空");
    }
    if (req.host.empty()) {
        return common::result::Result<void>::failure("机器 IP (host) 不能为空");
    }
    if (req.grpc_port <= 0 || req.grpc_port > 65535) {
        return common::result::Result<void>::failure("grpc_port 必须在 1-65535 之间");
    }
    if (req.ssh_port <= 0 || req.ssh_port > 65535) {
        return common::result::Result<void>::failure("ssh_port 必须在 1-65535 之间");
    }
    if (req.ssh_username.empty()) {
        return common::result::Result<void>::failure("SSH 用户名不能为空");
    }
    if (req.ssh_password.empty()) {
        return common::result::Result<void>::failure("SSH 密码不能为空");
    }
    if (req.scheduler_address.empty()) {
        return common::result::Result<void>::failure("scheduler_address 不能为空");
    }
    if (req.max_tasks <= 0) {
        return common::result::Result<void>::failure("max_tasks 必须大于 0");
    }
    if (req.worker_binary_path.empty()) {
        return common::result::Result<void>::failure("worker_binary_path 不能为空");
    }
    if (req.remote_dir.empty()) {
        return common::result::Result<void>::failure("remote_dir 不能为空");
    }
    return common::result::Result<void>();
}

std::string WorkerDeployService::generateWorkerConfig(const WorkerDeployRequest& req) {
    // The worker's advertised address (what the scheduler dials back to) is
    // host:grpc_port.
    std::string advertise_address = req.host + ":" + std::to_string(req.grpc_port);

    std::ostringstream ss;
    ss << "# Auto-generated by TaskFlow scheduler worker deployment\n";
    ss << "server:\n";
    ss << "  grpc_port: " << req.grpc_port << "\n";
    ss << "  advertise_address: " << yamlDoubleQuote(advertise_address) << "\n";
    ss << "  tls:\n";
    ss << "    enabled: false\n";
    ss << "\n";
    ss << "scheduler:\n";
    ss << "  address: " << yamlDoubleQuote(req.scheduler_address) << "\n";
    ss << "  tls:\n";
    ss << "    enabled: false\n";
    ss << "\n";
    ss << "worker:\n";
    ss << "  name: " << yamlDoubleQuote(req.name) << "\n";
    ss << "  max_tasks: " << req.max_tasks << "\n";
    ss << "  resource_tags:";
    if (req.resource_tags.empty()) {
        ss << " []\n";
    } else {
        ss << "\n";
        for (const auto& tag : req.resource_tags) {
            ss << "    - " << yamlDoubleQuote(tag) << "\n";
        }
    }
    ss << "\n";
    ss << "log:\n";
    ss << "  level: " << yamlDoubleQuote(req.log_level.empty() ? "info" : req.log_level) << "\n";
    ss << "  file_path: logs/worker.log\n";
    ss << "\n";
    ss << "task_log:\n";
    ss << "  dir: logs/tasks\n";
    ss << "  retention_days: 30\n";

    return ss.str();
}

common::result::Result<WorkerDeployResult> WorkerDeployService::deploy(const WorkerDeployRequest& req) {
    auto v = validate(req);
    if (!v.ok()) {
        return common::result::Result<WorkerDeployResult>::failure(v.error());
    }

    WorkerDeployResult result;
    result.worker_name = req.name;
    result.address = req.host + ":" + std::to_string(req.grpc_port);

    common::util::SshExecutor ssh(req.host, req.ssh_port, req.ssh_username, req.ssh_password);

    // Step 1: test connectivity.
    {
        DeployStepLog log{"SSH 连接测试", false, ""};
        auto t = ssh.testConnection(15);
        if (!t.ok()) {
            log.message = t.error();
            result.steps.push_back(log);
            result.success = false;
            result.message = "SSH 连接失败: " + t.error();
            return result;
        }
        log.success = true;
        log.message = "连接成功 " + req.ssh_username + "@" + req.host + ":" + std::to_string(req.ssh_port);
        result.steps.push_back(log);
    }

    // Step 2: create working directories on the remote host.
    {
        DeployStepLog log{"创建远程目录", false, ""};
        std::string mkdir_cmd =
            "mkdir -p " + req.remote_dir + "/logs/tasks";
        auto r = ssh.execute(mkdir_cmd, 30);
        if (!r.ok()) {
            log.message = r.error();
            result.steps.push_back(log);
            result.success = false;
            result.message = "创建远程目录失败: " + r.error();
            return result;
        }
        const auto& cr = r.value();
        if (cr.exit_code != 0) {
            log.message = "exit=" + std::to_string(cr.exit_code) + ": " + cr.output;
            result.steps.push_back(log);
            result.success = false;
            result.message = "创建远程目录失败: " + cr.output;
            return result;
        }
        log.success = true;
        log.message = req.remote_dir + "/logs/tasks";
        result.steps.push_back(log);
    }

    // Step 3: write the worker config file.
    std::string config_path = req.remote_dir + "/worker.yaml";
    result.config_path = config_path;
    {
        DeployStepLog log{"写入配置文件", false, ""};
        std::string content = generateWorkerConfig(req);
        auto w = ssh.writeFile(config_path, content, "644", 30);
        if (!w.ok()) {
            log.message = w.error();
            result.steps.push_back(log);
            result.success = false;
            result.message = "写入配置文件失败: " + w.error();
            return result;
        }
        log.success = true;
        log.message = config_path + " (" + std::to_string(content.size()) + " bytes)";
        result.steps.push_back(log);
    }

    // Step 4: check the worker binary exists on the remote host.
    {
        DeployStepLog log{"检查 worker 可执行文件", false, ""};
        std::string check_cmd = "test -x " + req.worker_binary_path + " && echo ok || echo missing";
        auto r = ssh.execute(check_cmd, 15);
        if (!r.ok()) {
            log.message = r.error();
            result.steps.push_back(log);
            result.success = false;
            result.message = "检查 worker 可执行文件失败: " + r.error();
            return result;
        }
        const auto& cr = r.value();
        if (cr.output.find("ok") == std::string::npos) {
            log.message = "未找到可执行的 worker: " + req.worker_binary_path;
            result.steps.push_back(log);
            result.success = false;
            result.message = log.message + "（请先在目标机器安装 worker 并设置可执行权限）";
            return result;
        }
        log.success = true;
        log.message = req.worker_binary_path;
        result.steps.push_back(log);
    }

    // Step 5: start the worker with nohup, detaching it from the SSH session.
    // The worker reads its config via --config and self-registers with the
    // scheduler over gRPC on startup.
    {
        DeployStepLog log{"启动 worker", false, ""};
        // cd into the working dir so relative log paths resolve correctly.
        std::string start_cmd =
            "cd " + req.remote_dir + " && "
            "nohup " + req.worker_binary_path + " --config " + config_path +
            " >> " + req.remote_dir + "/logs/worker.log 2>&1 &"
            " echo started_pid=$!";
        auto r = ssh.execute(start_cmd, 30);
        if (!r.ok()) {
            log.message = r.error();
            result.steps.push_back(log);
            result.success = false;
            result.message = "启动 worker 失败: " + r.error();
            return result;
        }
        const auto& cr = r.value();
        // nohup ... & returns immediately with exit code 0; the started_pid
        // marker confirms the launch command ran.
        if (cr.exit_code != 0) {
            log.message = "exit=" + std::to_string(cr.exit_code) + ": " + cr.output;
            result.steps.push_back(log);
            result.success = false;
            result.message = "启动 worker 失败: " + cr.output;
            return result;
        }
        log.success = true;
        log.message = "已启动: " + req.worker_binary_path + " --config " + config_path;
        if (!cr.output.empty()) {
            log.message += " (" + cr.output + ")";
        }
        result.steps.push_back(log);
    }

    // Step 6: briefly verify the process is still alive (not crashed on boot).
    {
        DeployStepLog log{"检查进程存活", false, ""};
        // Give the worker a moment to either boot or crash.
        ssh.execute("sleep 2", 10);
        // Match the binary path to avoid matching grep itself.
        std::string check_cmd =
            "pgrep -f " + req.worker_binary_path + " > /dev/null 2>&1 && echo alive || echo dead";
        auto r = ssh.execute(check_cmd, 15);
        std::string detail;
        if (r.ok()) {
            detail = r.value().output;
        } else {
            detail = r.error();
        }
        if (r.ok() && r.value().output.find("alive") != std::string::npos) {
            log.success = true;
            log.message = "worker 进程运行中";
        } else {
            // Process not detected — could be a race or a crash. Surface the
            // tail of the worker log to aid debugging rather than hard-failing.
            auto logtail = ssh.execute("tail -n 20 " + req.remote_dir + "/logs/worker.log 2>&1", 10);
            std::string tail = logtail.ok() ? logtail.value().output : "";
            log.success = false;
            log.message = "未检测到 worker 进程，可能启动失败或已退出。日志末尾:\n" + tail;
            result.steps.push_back(log);
            result.success = false;
            result.message = "worker 启动后未检测到进程，请检查远程日志: " +
                             req.remote_dir + "/logs/worker.log";
            return result;
        }
        result.steps.push_back(log);
    }

    result.success = true;
    result.message = "worker 部署成功，已通过 SSH 启动。worker 将自动向 scheduler (" +
                     req.scheduler_address + ") 注册，稍后将出现在节点列表中。";
    return result;
}

}  // namespace taskflow::scheduler::service
